[variables]
NIXPACKS_JDK_VERSION = "17"

[phases.build]
cmds = ["./gradlew bootJar -x test"]

[start]
cmd = "java $JAVA_OPTS -jar build/libs/synk-0.0.1-SNAPSHOT.jar --debug=false --logging.level.root=INFO --logging.level.org.springframework=INFO --logging.level.org.hibernate=INFO --logging.level.com.zaxxer.hikari=INFO --spring.jpa.show-sql=false --spring.jpa.properties.hibernate.format_sql=false"
